- name: ThoughtDecomposition
  domain: ${env| custom_domain}
  params:
    max_depth: 6
    max_steps: 6
    search_type: bfs
    b: 1
- name: ThoughtGenerator
  domain: ${env| custom_domain}
  llm: ${sub|thought_generator}
- name: StateEvaluator
  domain: ${env| custom_domain}
  llm: ${sub|state_evaluator}
  params:
    evaluation_type: vote
- name: SearchAlgorithm
  domain: ${env| custom_domain}
  llm: ${sub|json_res}
  use_llm_completion: true