- name: ThoughtDecomposition
  params:
    method: human
    max_depth: 3
    max_steps: 10
    search_type: bfs
- name: ThoughtGenerator
  llm: ${sub|json_res}
  params:
    generation_n: 1
  # use_default_prompt: true
  # prompts:
  #   - role: system
  #     template: examples/ToT_wf/agent/prompt_test/test.prompt
  #   - role: user
  #     template: examples/ToT_wf/agent/prompt_test/test.prompt
  prompt_elements:
    examples: 
    user: sample_user.prompt
- name: StateEvaluator
  llm: ${sub|json_res}
  params:
    evaluation_n: 1
    evaluation_type: vote
- name: SearchAlgorithm
  llm: ${sub|gpt}
  params:
    b: 3
    prune: true

  